FROM python:3.7.9-slim-buster


RUN mkdir -p /usr/src/app/
WORKDIR /usr/src/app/

RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6  -y

COPY ./requirements-server.txt .
RUN pip install --no-cache-dir -r requirements-server.txt


